version: "2"
run:
  tests: true
linters:
  enable:
    - gocognit
    - gocyclo
    - revive
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    gocognit:
      min-complexity: 20
    gocyclo:
      min-complexity: 15
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - .*_test\.go$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
