name: CD Pipeline (GoReleaser Tagged Release)

on:
  push:
    tags:
      - 'v*' # Disparo restringido exclusivamente a tags oficiales de versión (ej. v1.2.0)

permissions:
  contents: write # Permiso necesario para crear la Release en GitHub y subir los binarios generados

jobs:
  goreleaser:
    name: Build & Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code (Full Git History)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Esencial: GoReleaser necesita todo el historial de commits y tags para versionar y generar changelogs

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
